version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    reviewers:
      - erbridge

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    reviewers:
      - erbridge
    versioning-strategy: increase
