language: node_js
node_js:
  - "8"
cache: yarn
before_deploy: yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "s178w9fhREm/FUe4Lkafb6R1nLht8eGPMO3fa3GO5P7Nw8s2yPUISC3om77xlnZTwyJabcC9KxNu/YNw5NDgk4pO0T2uM7uQdTteCgM8tQh8K33TEZpvCLvofKlCGF6ypW7zawRv6XWtF0xjJe4Al399HbphardHaI2+l9rc63bcUz3Iegf2LisOdESqNQVq97MEz2QFxqrQsZqicchmfDHGD6oUjJDvvnCZcpHweHEr14H6ji4WJGYYsO8LLRoiC6gNTdIlJ15F56XKm3/U6lGlthX5C3pRCD65sai+1Yh6/wXQTPoD14UFRfs9YYXyYoOdP3pxMPCAOS4zHo3m8EnzND1VMSIFmnFzC7v5RO/mEnPoeKbQcDhTSEPZ/gcB5ruhNHIdbhY36qV//AyhENwkt4t9T3+HndV5NKuI7cTuC7TKxjo6QKQj/aB9cD3N/wJFzTGU5IlkoHYh/l7T8JZUYZQOfhhdRWUhRCSlCYRfLhwg7rVOQPEqPcRHQw1mJ10qdnB5n+dZTPB39qDQ3ch0xcsA3z78gJdbluh40jUqSHSRuRWy7+FE26mFZDdSSEKHb87pvg3sIcoK4fRRox30L6ZDQJWx2aTiQNVxF3VneBwWwbCFeDnWxQHi6KOunwcQ/UCT7Ee73ecvp8zaCoAW4WS3iOHHHt+dy8w0kO8="
