language: node_js
node_js:
- '8'
cache: yarn
before_deploy: yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: R5GR3H6S5oyIThT1g1z1oW2x4PvnrkxFHanJS7C6PaMrpjDd8NE905d4APlJ+56PltED4SHu6a1t/JXNHao+MlvO6Db/0tGFoPT3FCN03+DtU6JhO10OIR6HPCUMG44heSsSyDknIjycd7OeVEJzXJEskG/50PJverZGcOHgvXx3NcQHq7m7t4znOoVhhrAgy6rK4Bp3yb3AGNwmll/OwDLwHONWwKbt2YEClZmCePnQSQ+lA2yyzaOMYPKdMFRpjYkO+mYBNzBSp/iDvl5R9Bo957Rpa+Bw5M/DFjyqp6GwTX+DN72jYV9CPDr8LHS19vQKMGGHhfFi0jM6xigArp9oVUNGjmdfRIe0DYSBwIgEpM4zufAJvsCilIU8UuGkPFYfHSX2DpvfKQzZfPeAu39Xv5007uTQjQdaONXZTlAypzI6nK8VODBsYWBjBcxiJk80plJFg3i4z22CL6R5QvKFNHdMI31+bEgSCFjD1HqrlIgGB0ZvmvCKc67kEVosNGqiKjQnO3+Z1VRb6hJFHbK9ilqZz1idFd/qeN43mnglnHPCoJBz/qY6PsyulMl6FC8D9FE6I6HQU5yMRPgQr2yz8g1hiwjWRjJlp8meL4BaYmck2G+b0EeMJnjD8fNnxRHOnyUv+J6KFt5gZPVlGxtbhAq72UysVOpfiU14FmY=
